### ISSUE TITLE
Модель клетки все равно отвечает за визуализацию

### ISSUE THREAD

**Issue by Znack** [clicktronix/GameOfLife#11]
Она управляет тем, как стоит рисовать клетку, а не Представление. Если это сделано осознанно, надо привести причины сюда в комментарий :)

**Comment by clicktronix** [comment]
Модель клетки просто содержит информацию о том, как отрисовывать клетку, весь процесс отрисовки находится во вью. В этой модели нет обращения к DOM, просто хранится цвет клетки и размер. Свойства передаются во вью, где используя эти свойства происходит добавление клеток на сцену канваса и их отрисовка. Исходя из этого, я считаю, что модель клетки находится на своём месте:)

**Comment by Znack** [comment]
Неее, я думаю, это неверное в целом мнение, что стоит хоть что-то модели знать про визуализацию :)
А если у нас будут темы (ну там синия, оранжевая и тд) на выбор пользователя? :) 
Визуализация целиком должна быть создаваема и управляема через view, можно только в модели конфиги кое-какие хранить для вьюшек, просто потому функциональность иногда заставляет, но и то этого надо избегать столько, сколько можно

**Comment by Znack** [comment]
Вот здесь еще один явный пример, что лучше предупреждать перед закрытием ишью)
Ты просто перенес Cell.js в папку view? при этом у тебя в модели так же идет импорт этого файла и ты так же в модели игрового поля сохраняешь теперь уже инстансы вью? :)

**Comment by clicktronix** [comment]
Ну я думал о том, что это будет неверно просто переместить Cell.js. Но с другой стороны иногда в MVC допускается использование моделью сущностей представления. Я по идее всего лишь беру эту клетку и создаю массив. Также можно туда передать и просто сущность с нулями-еденицами, чтобы в консоли отображалась. Просто дробить клетку на 2 сущности мне показалось более не логичным, нежели перенос её во вью :))

**Comment by clicktronix** [comment]
Убрал клетку обратно в модель. Методы отрисовки перенес во View
