### ISSUE TITLE
Добавить use cases в тесты

### ISSUE THREAD

**Issue by Znack** [clicktronix/GameOfLife#13]
Не тестируются крайние случаи, например попытка создать клетку за пределами или обращение к таковой.
Не тестируется клик по клетке, совсем нет тестов на внешние элементы управления и тд.
Каждый модуль, и каждый метод в модулях должны иметь минимум по тесту :)

**Comment by clicktronix** [comment]
Как и с помощью чего тестировать элементы управления? :) Весь вечер проискал, как реализовать тесты обработки кликов (допустим вызывается ли функция updateAllCells при нажатии на кнопку), в итоге окончательно запутался)

**Comment by Znack** [comment]
Это для риззомы вопрос :)

**Comment by clicktronix** [comment]
Добавил use cases

**Comment by Znack** [comment]
А что делают такого рода проверки? почему тесты теперь так странно организованы? по сути у тебя это уже не юнит тесты, а целые енд-ту-енд :)

```
        const $clearButton = $('.action-buttons__js-clear-button');
        $clearButton.click(function () {
            view.draw(model.getCells());
        });

        $clearButton.click();
        sinon.assert.called(clearSpy);
```

**Comment by clicktronix** [comment]
Ну тут проверяем, вызывается ли метод `view.draw` при нажатии на кнопарь)) я это пытался затестить)

**Comment by Znack** [comment]
Ну смотри, в рамках юнит тестов всегда надо что-то конкретное тестить :) Например, метод foo у класса Bar, а тут конкретно что у чего тестируется?)

**Comment by clicktronix** [comment]
Просто вызов метода. Получается надо тестировать, допустим на этом примере, метод model.getGells()? создается ли массив при нажатии или нет?

**Comment by Znack** [comment]
Ну в данном случае я даже не знаю, конкретно тестировать, могу лишь сказать, что каждый тест должен иметь четкую цель в виде конкретной какой-то функции, так что для всех трех классов надо все методы протестировать на всех юз кейсах :)

**Comment by clicktronix** [comment]
Добавил тестов кнопок, оставил свои енд ту енд тесты)) протестировал функции `getCells` и `makeAlive/Dead` и отрисовку контура
