### ISSUE TITLE
Почему toggleCellAt возвращает функцию?

### ISSUE THREAD

**Issue by Znack** [clicktronix/GameOfLife#14]
При этом в тестах 
```
view.toggleCellAt(cells, 2, 2)
``` 
просто вот такая строка, то есть возвращаемая функция даже не вызывается

Я так понимаю, это нужно, чтобы в замыкании сохранить координаты для дальнейшего вызова по клику, но я бы советовал при передаче в onClick отдельно создать обертку, чем корявое API у класса делать, чтобы подпилить его под нужды внешнего мира :)

**Comment by clicktronix** [comment]
Избавился от замыкания в toggleCellAt

**Comment by Znack** [comment]
А у тебя точно нормально работает функционал после этого?) просто мне кажется должны быть траблы с `i` и `j` %)

**Comment by clicktronix** [comment]
Ну я сейчас еще раз потестил, на всякий случай)) всё правильно работает)

**Comment by Znack** [comment]
Ну в любом случае мне не нравится, что ты в цикле прямо объявляешь функцию, можешь плиз отрефакторить, чтобы у тебя по максимуму все там аккуратно и чисто было без лишней вложенности?

**Comment by clicktronix** [comment]
Я конечно попробую как то от этого уйти) но пока не знаю как)

**Comment by Znack** [comment]
Ну я тебе не буду говорить как, жду придуманного тобой решения :)

**Comment by clicktronix** [comment]
Перенес вызов функции toggle в метод, а в bind передал аргументы. Работает :))

**Comment by Znack** [comment]
Так а зачем тебе все таки та лишняя функция? :)
```
$startButton.on('click', function () {
    start();
});
```
Хотя можно, конечно, так:
```
$startButton.on('click', start);
```

**Comment by clicktronix** [comment]
И вправду, что то я уже по инерции исправляю, не вдумываясь. Исправил, теперь намного красивше)

**Comment by clicktronix** [comment]
и `$startButton.on('click', start);` наверное к 18 ишью относится :D. Я поправил оба, и это и 18-ое
