### ISSUE TITLE
Привести к стандартам

### ISSUE THREAD

**Issue by Znack** [clicktronix/GameOfLife#17]
Есть несколько нарушений, тут только парочка из них, причем довольно неочевидные специально вынес, остальное искать самому :)

- у контроллера лишнее замыкание cells, лучше использовать const и всегда заново переменную создавать
- именование классов не по  БЭМ
- нарушение правила "Избегать мутаций одной переменной сразу в нескольких функциях"
- уйти где удобно от обычных циклов в методам массива (например, reduce точно можно заюзать для подсчета соседей, при этом предикат вынося в отдельный метод)

**Comment by clicktronix** [comment]
По поводу замыкания cells. Если делать cells константой, и заново создавать переменную, то мы всегда будем терять координаты измененных на предыдущей итерации клеток. А сейчас в контроллере массив создаётся всего 1 раз и в нём обновляется по сути только статус клеток.

**Comment by Znack** [comment]
Так у тебя целиком весь массив пересоздается по каждом событию :) Я в итоге не вижу, что именно и как этот подход позволяет сохранять из предыдущей итерации и зачем оно надо?)

```
        let cells = model.newEmptyArray();
        $body.bind('step', function () {
            cells = model.updateAllCells(cells);
        });
        $body.bind('clear', function () {
            cells = model.newEmptyArray();
        });
```
Я даже проверил, что `updateAllCells` именно создает массив новый, а не обновляет старый (это ты кстати правильно сделал)

**Comment by clicktronix** [comment]
Я может туплю)) но если сделать 
```
const cells = model.newEmptyArray();
        $body.bind('step', function () {
            let cells = model.updateAllCells(cells);
        });
```
То работать не будет:) Попытаюсь объяснить:
Если я сделаю `cells` константой, то всё будет ломаться на первой итерации. При клике на клетку, в методе `draw` вызывается метод `toggleCellAt` и меняет значение клетки, соответственно изменяется массив. Далее при нажатии на кнопку старт, запускается метод `updateAllCells`, который на основе массива, хранящегося в `cells`, создает новый массив, который переприсваивается в cells, и эта итерация повторяется. 
В общем)) когда cells константа, то массив клеток, которые я накликал, сохраняется в ней перманентно и на следующих итерациях ничего не произойдет, потому что рабочий массив не обновляется. Если создавать новую переменную, то будет фактически тоже самое. 
Я не знаю какой тут можно применить трюк :)) Но я думаю, что не нужно делать `cells` константой

**Comment by Znack** [comment]
А, все, понял, ты в замыкании сохраняешь прошлое состояние клеток, чтобы при следующем событии его передавать. Это плохая архитектура, получается, у тебя модель не способна сама хранить состояние и без контроллера делать ходы :) Кстати, событие "Ход" стоило бы модели генерить, потому что это логика самой игры, а не пользовательское событие. Просто модель должна знать, сейчас на паузе игра или нет, и если не на паузе, то эмитить ходы сама должна уметь, я думаю. По крайней мере инкапсулировать это точно стоит.
У тебя сейчас слишком много зависимостей между слоями и они друг без друга существовать совсем не могут (а как минимум модель должна быть более менее самостоятельной)

**Comment by clicktronix** [comment]
Инкапсулировал модель. Теперь массив ячеек хранится в ней

**Comment by clicktronix** [comment]
Сделал всё, кроме пункта с reduce. Сложноватый перебирающий метод. Можно чуть поподробнее расписать как его можно реализовать))

**Comment by Znack** [comment]
Тогда это вопрос в риззому)

**Comment by Znack** [comment]
И ты не все по стандартам исправил, не забудь, что я сразу сказал, что некоторые пункты я специально в ишью не написал и тебе самому надо найти)

**Comment by clicktronix** [comment]
окей, понял, поищу)

**Comment by clicktronix** [comment]
Сделал поиск соседей с помощью reduce :)

**Comment by Znack** [comment]
Ну не забудь, что это не единственное место, где стоило бы редьюс использовать, плюс другие правила стандартов проверь)

**Comment by clicktronix** [comment]
Вынес условия в отдельный метод, обозначил приватные/публичные методы. В методе `_getNeighborCount` вынес проверку статус в предикат.
