### ISSUE TITLE
События контроллера убрать с body

### ISSUE THREAD

**Issue by Znack** [clicktronix/GameOfLife#18]
В идеале все должно работать так, что мы можем подменить только View, и, например, суметь запустить приложение на ноде с интерфейсом через консоль :) Так что привязка событий к <body> лишняя, в js ты можешь события генерить относительно любых объектов и я бы советовал события эмитить как раз от view, чтобы в контроллере просто написать
```
        const view = new View(length);
        view.on('step', function () {
            cells = model.updateAllCells(cells);
            view.draw(cells);
        });
```

**Comment by Znack** [comment]
Я думаю, лучше ишью не закрывать, а писать коммент автору, что ты попытался исправить, а закрывать уже будет составитель (автор) ишью)
У тебя например, как-то криво решено это. Почему бы просто не отнаследоваться от EventEmitter-а и не емитить события прямо от имени самой view?
Тут же у тебя опять нарушение стандарта идет, что мы извне создаем перменные, чтобы их передать дальше по коду и ждать пока они там будут изменены (в данном случае пока триггер события на них будет вызван).

**Comment by clicktronix** [comment]
Переделал. Отнаследовал view от EventEmmiter'a

**Comment by Znack** [comment]
А зачем ты емит в отдельную переменную сохранил?
```
const emit = this.emit.bind(this);
```

**Comment by clicktronix** [comment]
При нажатии на `$stepButton` и `$clearButton` контекст теряется

**Comment by Znack** [comment]
ну смотри, пытаясь решить небольшую архитектурную грязь (когда, контроллер откровенно на бади подписывался) ты сначала ввел отдельную ненужную сущность, потом убрав ее через наследование ты сделал еще тут конкретно в конструкторе грязь :) Тебе надо не забывать, что ты не должен тупо брать и напрямую решать ишью, которые я тебе ставлю, а ты должен делать проект в целом более чистым и красивым - я ишью ставлю чтобы немного направить в очевидных местах и их решение не должно ничего портить)

**Comment by Znack** [comment]
Я это к тому, что твой конструктор сейчас очень раздутый получается, причем без особой нужды, плюс вот приходится всякие костыли делать, чтобы другие костыли поддерживать (я про раздутость тут как раз)

**Comment by clicktronix** [comment]
немного не ясно, что необходимо исправить. И нужно ли вообще?)

**Comment by Znack** [comment]
Конечно нужно :)
У тебя очень раздутый конструктор, почему ты биндинг событий сразу туда запихал? Мне например это сразу как антипаттерн видится - объявление этих хендлеров в конструкторе сразу)

**Comment by clicktronix** [comment]
Теперь понял, раздутость конструктора идёт от объявления событий в нём. Я до этого подумал, что раздутость, это следствие использования `const emit = this.emit.bind(this);` :D

**Comment by Znack** [comment]
Да, я в целом про весь метод :)

**Comment by clicktronix** [comment]
Убрал хэндлеры в метод `manage`. Конструктор стал в разы меньше)

**Comment by Znack** [comment]
Если честно, я ожидал, что ты еще немного красивей сделаешь, чем просто в manage перенесешь (кстати название тоже лучше сменить 😃 ) - если у тебя есть класс, зачем в методах создавать отдельные функции, особенно учитывая, что тебе там внутри нужен контекст? Почему это не сделать как методы класса так же?

**Comment by clicktronix** [comment]
Еще раз переделал, раскидал функции обработки по методам
